name: Scala CI

on:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Start containers
        run: docker-compose -f "subscriptions/src/test/resources/docker-compose.yml" up -d
      - name: Run tests
        env:
          DB_TEST: ${{ secrets.HOST_TEST }}
          USER_TEST: ${{ secrets.USER_TEST }}
          PASSWORD_TEST: ${{ secrets.PASSWORD_TEST }}
        run: sbt test
      - name: Log if failure broker
        if: ${{ failure() }}
        run: docker logs kafka
      - name: Log if failure
        if: ${{ failure() }}
        run: docker ps -a
      - name: Stop containers
        if: always()
        run: docker-compose -f "subscriptions/src/test/resources/docker-compose.yml" down
